# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
