# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160402_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
