# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160411_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
