# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160413_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
