# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 03:20
from __future__ import unicode_literals

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20160502_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_profile, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_pet, verbose_name='logo'),
        ),
    ]
