# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-03 21:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160508_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_Pet',
            new_name='pets',
        ),
    ]
